# Generated by Django 5.1.7 on 2025-03-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_cart_product_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('dozen', 'Dozen'), ('litre', 'Litre'), ('500g', '500 Gram Pack'), ('piece', 'Piece')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
